DELETE http://localhost:3001/api/persons/4 HTTP/1.1
###
POST https://sheltered-ravine-40342.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Dan Test",
    "number": "994",
    "id": 8
}